cursor #ff7e9f
cursor_text_color background

foreground #f1dee1
background #1a1113

selection_foreground #1a1113
selection_background #be4872
url_color #ff88a7

# black / gray
color0  #150c0e
color8  #91747a

# red
color1  #ffc6bf
color9  #ff7d6e

# green / secondary
color2  #fad0da
color10 #f286a1

# yellow / tertiary
color3  #ffd1b9
color11 #ff945d

# blue / primary
color4  #ffd0dc
color12 #ff7e9f

# magenta / tertiary muted
color5  #ffc3a4
color13 #ff8e53

# cyan / secondary muted
color6  #f8bdcc
color14 #f07393

# white
color7  #dbc0c5
color15 #f1dee1
