cursor #6eccff
cursor_text_color background

foreground #dfe3e7
background #0f1417

selection_foreground #0f1417
selection_background #38b7f3
url_color #78d0ff

# black / gray
color0  #0a0f12
color8  #737e86

# red
color1  #ffc6bf
color9  #ff7d6e

# green / secondary
color2  #bfd8e8
color10 #82b5d3

# yellow / tertiary
color3  #fbf1ff
color11 #e095ff

# blue / primary
color4  #c0e9ff
color12 #6eccff

# magenta / tertiary muted
color5  #f5dcff
color13 #dd8bff

# cyan / secondary muted
color6  #b0cfe3
color14 #73accd

# white
color7  #bec8cf
color15 #dfe3e7
