font_size 15.0
background_opacity 0.5
# background #111111
window_margin_width 8 12 12 12
confirm_os_window_close 0
enable_audio_bell no

# END_KITTY_THEME
shell_integration disabled
#hide_window_decorations titlebar-only
hide_window_decorations yes

# Include wallpaper colors
#include colors-wallust.conf
include colors-matugen.conf
# BEGIN_KITTY_THEME
# Ayu
#include current-theme.conf
pixel_scroll yes
wheel_scroll_multiplier 5.0
