[config]
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors-matugen.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.luminous]
input_path = "~/.config/matugen/templates/luminous.toml"
output_path = "~/.config/xdg-desktop-portal-luminous/config.toml"
post_hook = 'sh -lc "systemctl --user restart xdg-desktop-portal-luminous.service xdg-desktop-portal.service; ~/.local/bin/tg-theme-request"'

[templates.tofi]
input_path = '~/.config/matugen/templates/tofi-colors'
output_path = '~/.config/tofi/colors'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
 
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
 
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'
 
[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
#post_hook = 'bash -lc "sleep 0.1; $HOME/.local/bin/pywalfox update"'
